CREATE TABLE answer (
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	message_answer VARCHAR(1000) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	solution BOOLEAN NOT NULL DEFAULT FALSE,
	
	PRIMARY KEY (id),	
)