CREATE TABLE topic (
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	message_topic VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	status_topic BOOLEAN NOT NULL DEFAULT FALSE,
	
	PRIMARY KEY (id),	
)